/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.jtodd.jni.jrmatrix;

import org.jtodd.jni.JRashunalMatrix;
import org.jtodd.jni.RMatrixJNI;

public class App {
    public static void main(String[] args) {
        RMatrixJNI rmj = new RMatrixJNI();
        int data[][][] = {
            { { 1    }, { 2 }, { 3, 2 }, },
            { { 4, 3 }, { 5 }, { 6    }, },
        };
        JRashunalMatrix u = rmj.factorMatrix(data);
        System.out.println(u);
    }
}
